name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Amsterdam
          config_display: large
          base_indepth: yes
          base_hireable: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_timestamps: yes
          plugin_activity_days: 0
          plugin_activity_filter: all
          plugin_activity_visibility: public
          plugin_habits_days: 30
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_sections: most-used, recently-used
          plugin_reactions: yes
          plugin_reactions_display: relative
          plugin_stargazers: yes
